### ISSUE TITLE
Highlighting only in graphql files, not in ts files

### ISSUE THREAD

**Issue by Redskinsjo** [B2o5T/graphql-eslint#1573]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Graphql-eslint catches errors in graphql files but not in ts files

**To Reproduce** Steps to reproduce the behavior:
https://github.com/Redskinsjo/repro-gql-eslint
just clone and run dev this repo. add a duplicate field in GetUser query, it works: highlighting duplicates. but try to add a duplicate field in schema.ts, and it doesn't work: no highlighting.

**Expected behavior**

should highlight in both cases

**Environment:**

- OS: macos 13.3
- `@graphql-eslint/eslint-plugin`: v3.18.0
- Node.js: v19.5.0

**Additional context**

happy passover :)

**Comment by B2o5T** [comment]
you need setup `processor` for operations files too https://github.com/Redskinsjo/repro-gql-eslint/blob/48ef0b505b075816a85f8da0fd3c6f79ff6df15d/.eslintrc.json#L34-L35

**Comment by B2o5T** [comment]
you don't need to add resolvers because these files don't contain GraphQL SDL

**Comment by B2o5T** [comment]
> But it doesn't highlight when I add a duplicate field in the schema

do you have an error output in the terminal or not? also `next lint` seems doesn't work with graphql-eslint https://github.com/B2o5T/graphql-eslint/issues/1095#issuecomment-1160907823

**Comment by B2o5T** [comment]
Because you don't enable any SCHEMA rules, you have enabled only 1 operations rule https://github.com/Redskinsjo/repro-gql-eslint/blob/235151e16cc42b0f46840042e8f1aebd0e79447f/.eslintrc.json#L50

I'll close this issue because there is nothing wrong with graphql-eslint

1. see another time my comment (you have exactly the same problem https://github.com/B2o5T/graphql-eslint/issues/1095#issuecomment-1160907823)
2. see various working examples of any usage https://github.com/B2o5T/graphql-eslint/tree/master/examples
