### ISSUE TITLE
Implement rules from graphql-schema-linter

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [B2o5T/graphql-eslint#76]
See https://github.com/cjoudrey/graphql-schema-linter#built-in-rules

**Comment by ilyavolodin** [comment]
Some of those rules are already implemented. Some others are not possible to implement with ESLint (unfortunately). Specifically:
arguments-have-descriptions - not implemented
defined-types-are-used - not possible to implement, requires full schema
deprecations-have-a-reason - implemented [require-deprecation-reason](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-deprecation-reason.md)
descriptions-are-capitalized - not implemented
enum-values-all-caps - implemented [naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
enum-values-have-descriptions - implemented [require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
enum-values-sorted-alphabetically - not implemented
fields-are-camel-case - implemented [naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
fields-have-descriptions - implemented [require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
input-object-fields-sorted-alphabetically - not implemented
input-object-values-are-camel-cased - implemented [naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
input-object-values-have-descriptions - implemented [require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
relay-connection-types-spec - not implemented (tricky to implement correctly, without too many false positives or negatives)
relay-connection-arguments-spec - not implemented (see above)
type-fields-sorted-alphabetically - not implemented
types-are-capitalized - implemented [naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
types-have-descriptions - implemented [require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)

**Comment by aldeed** [comment]
I created some of these for graphql-schema-linter so I could potentially implement here. Not sure how different it is.

Seems like the plan would be:
- new "alphabetize" rule
- new "capitalize-descriptions" rule

Both have `on` config for what types (similar to `require-description` config)

And update `require-description` rule to add "FieldArgument" support

**Comment by dotansimha** [comment]
@aldeed it's not that different in terms of schema linting, the main difference is the fact that we deal with AST per file (since it's ESLint based) and not over the schema. And we also lint operations. 

We are always open for contributions, so PRs are welcome ;)

**Comment by dotansimha** [comment]
> defined-types-are-used - not possible to implement, requires full schema

@kamilkisiela this is the one you added in https://github.com/dotansimha/graphql-eslint/pull/243 , right?

**Comment by kamilkisiela** [comment]
No, it doesn't involve operations and fragments, we just check if all types are accessible when querying from root

**Comment by dotansimha** [comment]
@kamilkisiela I think the original one references here is not using operations at all, it just makes sure that all types defined in the schema are used ( = reachable)

**Comment by kamilkisiela** [comment]
Then yes

**Comment by B2o5T** [comment]
I'll close this issue since all most necessary rules were implemented

|graphql-schema-linter|graphql-eslint|
|:-|:-|
|arguments-have-descriptions|someone need this?
|defined-types-are-used|[no-unreachable-types](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/no-unreachable-types.md)
|deprecations-have-a-reason|[require-deprecation-reason](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-deprecation-reason.md)
|descriptions-are-capitalized|someone need this?
|enum-values-all-caps|[naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
|enum-values-have-descriptions|[require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
|enum-values-sorted-alphabetically|[alphabetize](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/alphabetize.md)
|fields-are-camel-case|[naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
|fields-have-descriptions|[require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
|input-object-fields-sorted-alphabetically|[alphabetize](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/alphabetize.md)
|input-object-values-are-camel-cased|[naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
|input-object-values-have-descriptions|[require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
|relay-connection-arguments-spec|[relay-arguments](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/relay-arguments.md)
|relay-connection-types-spec|[relay-connection-types](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/relay-connection-types.md)
|relay-page-info-spec|[relay-page-info](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/relay-page-info.md)
|type-fields-sorted-alphabetically|[alphabetize](https://github.com/B2o5T/graphql-eslint/blob/master/docs/rules/alphabetize.md)
|types-are-capitalized|[naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md)
|types-have-descriptions|[require-description](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/require-description.md)
