### ISSUE TITLE
Make `graphql-config` peer / optional dependency?

### ISSUE THREAD

**Issue by dotansimha** [B2o5T/graphql-eslint#946]
At the moment it's installed anyway, which might install a lot of other sub-deps.

**Comment by B2o5T** [comment]
Otherwise we need to install:
- @graphql-tools/graphql-file-loader
- @graphql-tools/code-file-loader
- @graphql-tools/load
- @graphql-tools/url-loader
- @graphql-tools/json-file-loader

All of them already included in `graphql-config`, so we simple install `graphql-config` and use him to load schema and operations from `graphql-config` file or via `parserOptions`.
I made a refactoring In this PR https://github.com/dotansimha/graphql-eslint/pull/545

**Comment by B2o5T** [comment]
@dotansimha As an idea, we can reduce the bundle by publishing `GraphQLRuleTester` as own package `@graphql-eslint/rule-tester` because only rule tester uses `@babel/code-frame` https://github.com/dotansimha/graphql-eslint/blob/master/packages/plugin/package.json#L37

**Comment by B2o5T** [comment]
this dependency is required even for programmatic usage, but in browser we don't use it (since there is no fs here)

I would like still keep it as `dependency`
