### ISSUE TITLE
Adding roles that require schema/operation file failure.

### ISSUE THREAD

**Issue by RoyLeibo** [B2o5T/graphql-eslint#947]
I have opened a question in Stack overflow for this issue: https://stackoverflow.com/questions/70943271/graphql-eslint-eslint-plugin-parseroptions-schema-error

**Comment by B2o5T** [comment]
Hi @RoyLeibo!

I'm not adding a lot here but I'm just labelling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It looks like already got it into `stage 0`! thank you for that!

Now in order to advance to `stage 1` we'll need a running reproduction.

After that maybe a failing test to advance it through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by RoyLeibo** [comment]
@B2o5T thank you for your answer.
As specified in stage 1, I have opened a repository with the simplest project possible to reproduce the error.
I have specified the issue in the README.md

Thanks!

**Comment by B2o5T** [comment]
Hi @RoyLeibo, some rules of `graphql-eslint` expect to receive **a full schema** (not partial like in your repo).
It's doesn't matter how you will provide it either via `graphql` file, `json` file or via endpoint URL.

**Comment by RoyLeibo** [comment]
@B2o5T Thank you for your answer!
I understood that the schemas are required, I was just unable to provide the path to the schemas.. no matter what have I tried. can you show me the code that accomplishes that?

**Comment by B2o5T** [comment]
@RoyLeibo You don't provide your schema for `graphql-eslint`.
Please read [the following instructions](https://github.com/B2o5T/graphql-eslint#extended-linting-rules-with-graphql-schema) that described in readme.

When I provided your partial schema
```diff
{
  "files": ["*.graphql"],
  "excludedFiles": ["*.ts, *.tsx", "*.generated.*"],
  "parser": "@graphql-eslint/eslint-plugin",
  "plugins": ["@graphql-eslint"],
+ "parserOptions": {
+   "schema": "./src/graphql/application/application.schema.graphql"
+ },
```

I received the following output
```
error [graphql-eslint] Error while loading schema
 Error: Cannot extend type "Query" because it is not defined.

Cannot extend type "Mutation" because it is not defined.

Unknown directive "@key".

Unknown type "Query".

Unknown type "Mutation".
```

Why this happens I described in the last comment

**Comment by RoyLeibo** [comment]
@B2o5T Thank you so much!

Last question, where did you describe how to solve the new error that pops up following the schema path is provided?

**Comment by B2o5T** [comment]
>  some rules of `graphql-eslint` expect to receive a full schema (not partial like in your repo).
