### ISSUE TITLE
@graphql-eslint/alphabetize autofix need execute 3 ~ 4 time to get fix

### ISSUE THREAD

**Issue by davidNHK** [B2o5T/graphql-eslint#955]
**Describe the bug**
@graphql-eslint/alphabetize  autofix on my production schema cannot get fix by execute once.

**To Reproduce**
Not sure? Just find some big enough scham and enable @graphql-eslint/alphabetize 

**Expected behavior**
Sort the schema

**Environment:**

- OS: mac
- `@graphql-eslint/...`:
- NodeJS:

**Additional context**

Keep get error similar to `  1496:3   error  "addComment" should be before "approveApplication"                           @graphql-eslint/alphabetize`

But if i execute again, i can the error is decreasing .

**Comment by B2o5T** [comment]
Hi @davidNHK, I think even similar rule from eslint `sort-keys` has similar behavior, if you have an idea how this can be fixed feel free to share

**Comment by B2o5T** [comment]
I will close this issue because this cannot be improved by `graphql-eslint`. ESLint does not allow more than 10 autofix passes for a rule.
https://github.com/eslint/eslint/blob/b93af98b3c417225a027cabc964c38e779adb945/lib/linter/linter.js#L44

Feel free to open related issue in `eslint` repo if you want to make this constant configurable or use `patch-package` to change this value.
